(eval-when-compile    (require 'color-theme))
(defun candera-color-theme ()
  "Color theme by Craig Andera, created 2011-07-01."
  (interactive)
  (color-theme-install
   '(candera-color-theme
     (;; Attempts to set the background color to black result in a
      ;; grey background.
      ;(background-color . "black")
      (background-mode . dark)
      (border-color . "white")
      (cursor-color . "yellow")
      (foreground-color . "white")
      (mouse-color . "white"))
     ((apropos-keybinding-face . underline)
      (apropos-label-face italic variable-pitch)
      (apropos-match-face . match)
      (apropos-property-face . bold-italic)
      (apropos-symbol-face . bold)
      (goto-address-mail-face . italic)
      (goto-address-mail-mouse-face . secondary-selection)
      (goto-address-url-face . link)
      (goto-address-url-mouse-face . highlight)
      (hl-line-face . hl-line)
      (ispell-highlight-face . isearch)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . bold)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:height 140 :foundry "unknown" :family "DejaVu Sans Mono"))))
     (CUA-global-mark-face ((t (:background "cyan" :foreground "black"))))
     (CUA-rectangle-face ((t (:background "maroon" :foreground "white"))))
     (CUA-rectangle-noselect-face ((t (:background "dimgray" :foreground "white"))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (:background "white"))))
     (border-glyph ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (buffers-tab ((t (:background "black" :foreground "white"))))
     (button ((t (:underline t))))
     (calendar-today-face ((t (:foreground "white" :underline t))))
     (change-log-acknowledgement ((t (:foreground "Firebrick"))))
     (change-log-conditionals ((t (:foreground "sienna"))))
     (change-log-date ((t (:foreground "VioletRed4"))))
     (change-log-email ((t (:foreground "sienna"))))
     (change-log-file ((t (:foreground "Blue1"))))
     (change-log-function ((t (:foreground "sienna"))))
     (change-log-list ((t (:foreground "Purple"))))
     (change-log-name ((t (:foreground "dark cyan"))))
     (clearcase-dired-checkedout-face ((t (:foreground "red"))))
     (clojure-test-error-face ((t (:background "orange1"))))
     (clojure-test-failure-face ((t (:background "orange red"))))
     (clojure-test-success-face ((t (:background "green" :foreground "black"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (completions-annotations ((t (:underline t))))
     (completions-common-part ((t (:stipple nil :background "unspecified-bg" :foreground "unspecified-fg" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cperl-array-face ((t (:foreground "darkseagreen"))))
     (cperl-hash-face ((t (:foreground "darkseagreen"))))
     (cperl-nonoverridable-face ((t (:foreground "SkyBlue"))))
     (cursor ((t (:background "yellow"))))
     (custom-button-face ((t (nil))))
     (custom-changed-face ((t (:background "blue" :foreground "white"))))
     (custom-documentation-face ((t (nil))))
     (custom-face-tag-face ((t (:underline t))))
     (custom-group-tag-face ((t (:underline t))))
     (custom-group-tag-face-1 ((t (:underline t))))
     (custom-invalid-face ((t (:background "red" :foreground "white"))))
     (custom-modified-face ((t (:background "blue" :foreground "white"))))
     (custom-rogue-face ((t (:background "black" :foreground "pink"))))
     (custom-saved-face ((t (:underline t))))
     (custom-set-face ((t (:background "white" :foreground "blue"))))
     (custom-state-face ((t (nil))))
     (custom-variable-button-face ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag-face ((t (:underline t))))
     (diary-face ((t (:foreground "gold"))))
     (diff-added ((t (:italic t :bold t :foreground "green" :slant italic :weight bold))))
     (diff-changed ((t (:italic t :bold t :foreground "magenta" :slant italic :weight bold))))
     (diff-context ((t (:foreground "grey50"))))
     (diff-file-header ((t (:bold t :background "grey70" :weight bold))))
     (diff-function ((t (:background "grey80"))))
     (diff-header ((t (:background "grey80"))))
     (diff-hunk-header ((t (:background "grey80"))))
     (diff-index ((t (:bold t :background "grey70" :weight bold))))
     (diff-indicator-added ((t (:italic t :bold t :foreground "green" :slant italic :weight bold))))
     (diff-indicator-changed ((t (:italic t :bold t :foreground "magenta" :slant italic :weight bold))))
     (diff-indicator-removed ((t (:italic t :bold t :foreground "red" :slant italic :weight bold))))
     (diff-nonexistent ((t (:bold t :background "grey70" :weight bold))))
     (diff-refine-change ((t (:background "grey85"))))
     (diff-removed ((t (:italic t :bold t :foreground "red" :slant italic :weight bold))))
     (ediff-current-diff-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-Ancestor ((t (:background "gray40" :foreground "cyan3"))))
     (ediff-odd-diff-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-C ((t (:background "Grey" :foreground "White"))))
     (erc-action-face ((t (:bold t :weight bold))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (:foreground "sandybrown"))))
     (erc-error-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (erc-input-face ((t (:foreground "Beige"))))
     (erc-inverse-face ((t (:background "wheat" :foreground "darkslategrey"))))
     (erc-notice-face ((t (:foreground "MediumAquamarine"))))
     (erc-pal-face ((t (:foreground "pale green"))))
     (erc-prompt-face ((t (:foreground "MediumAquamarine"))))
     (erc-underline-face ((t (:underline t))))
     (escape-glyph ((t (:foreground "brown"))))
     (eshell-ls-archive-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (eshell-ls-backup-face ((t (:foreground "Grey"))))
     (eshell-ls-clutter-face ((t (:foreground "DimGray"))))
     (eshell-ls-directory-face ((t (:bold t :foreground "MediumSlateBlue" :weight bold))))
     (eshell-ls-executable-face ((t (:foreground "Coral"))))
     (eshell-ls-missing-face ((t (:foreground "black"))))
     (eshell-ls-picture-face ((t (:foreground "Violet"))))
     (eshell-ls-product-face ((t (:foreground "sandybrown"))))
     (eshell-ls-readonly-face ((t (:foreground "Aquamarine"))))
     (eshell-ls-special-face ((t (:foreground "Gold"))))
     (eshell-ls-symlink-face ((t (:foreground "White"))))
     (eshell-ls-unreadable-face ((t (:foreground "DimGray"))))
     (eshell-prompt-face ((t (:foreground "MediumAquamarine"))))
     (file-name-shadow ((t (:foreground "grey50"))))
     (fixed-pitch ((t (:family "courier"))))
     (fl-comment-face ((t (:foreground "pink"))))
     (fl-doc-string-face ((t (:foreground "purple"))))
     (fl-function-name-face ((t (:foreground "red"))))
     (fl-keyword-face ((t (:foreground "cadetblue"))))
     (fl-string-face ((t (:foreground "green"))))
     (fl-type-face ((t (:foreground "yellow"))))
     (flash-paren-face-off ((t (nil))))
     (flash-paren-face-on ((t (nil))))
     (flash-paren-face-region ((t (nil))))
     (flexwiki-bold-face ((t (:weight normal))))
     (flexwiki-done-face ((t (:foreground "dim grey"))))
     (flexwiki-heading-1-face ((t (:height 1.5))))
     (flexwiki-heading-2-face ((t (:height 1.3))))
     (flexwiki-heading-3-face ((t (:height 1.1))))
     (flexwiki-italic-face ((t (:italic t :slant italic))))
     (flexwiki-property-face ((t (:foreground "green3"))))
     (flexwiki-question-face ((t (:foreground "red2"))))
     (flexwiki-strikethrough-face ((t (:strike-through t))))
     (flexwiki-todo-face ((t (:foreground "dark violet"))))
     (flexwiki-underline-face ((t (:underline t))))
     (flexwiki-wikiword-face ((t (:foreground "blue"))))
     (flyspell-duplicate ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-comment-delimiter-face ((t (:foreground "Firebrick"))))
     (font-lock-comment-face ((t (:foreground "OrangeRed"))))
     (font-lock-constant-face ((t (:foreground "Aquamarine"))))
     (font-lock-doc-face ((t (:foreground "LightSalmon"))))
     (font-lock-doc-string-face ((t (:foreground "DarkOrange"))))
     (font-lock-function-name-face ((t (:foreground "LightSkyBlue"))))
     (font-lock-keyword-face ((t (:foreground "Cyan"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "MediumOrchid4"))))
     (font-lock-reference-face ((t (:foreground "SlateBlue"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "LightSalmon"))))
     (font-lock-type-face ((t (:foreground "PaleGreen"))))
     (font-lock-variable-name-face ((t (:foreground "LightGoldenrod"))))
     (font-lock-warning-face ((t (:bold t :foreground "Pink" :weight bold))))
     (fringe ((t (:background "grey10"))))
     (gnus-cite-attribution-face ((t (:foreground "beige" :underline t))))
     (gnus-cite-face-1 ((t (:foreground "gold"))))
     (gnus-cite-face-10 ((t (:foreground "coral"))))
     (gnus-cite-face-11 ((t (:foreground "turquoise"))))
     (gnus-cite-face-2 ((t (:foreground "wheat"))))
     (gnus-cite-face-3 ((t (:foreground "light pink"))))
     (gnus-cite-face-4 ((t (:foreground "khaki"))))
     (gnus-cite-face-5 ((t (:foreground "pale green"))))
     (gnus-cite-face-6 ((t (:foreground "beige"))))
     (gnus-cite-face-7 ((t (:foreground "orange"))))
     (gnus-cite-face-8 ((t (:foreground "magenta"))))
     (gnus-cite-face-9 ((t (:foreground "violet"))))
     (gnus-emphasis-bold ((t (:bold t :foreground "light gray" :weight bold))))
     (gnus-emphasis-bold-italic ((t (:italic t :bold t :foreground "cyan" :slant italic :weight bold))))
     (gnus-emphasis-highlight-words ((t (:background "black" :foreground "gold"))))
     (gnus-emphasis-italic ((t (:italic t :foreground "cyan" :slant italic))))
     (gnus-emphasis-underline ((t (:foreground "white" :underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :foreground "white" :underline t :weight bold))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :foreground "white" :underline t :slant italic :weight bold))))
     (gnus-emphasis-underline-italic ((t (:italic t :foreground "white" :underline t :slant italic))))
     (gnus-group-mail-1-empty-face ((t (:foreground "Magenta"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "Magenta" :weight bold))))
     (gnus-group-mail-2-empty-face ((t (:foreground "aquamarine2"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "aquamarine2" :weight bold))))
     (gnus-group-mail-3-empty-face ((t (:foreground "Cyan"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "Cyan" :weight bold))))
     (gnus-group-mail-low-empty-face ((t (:foreground "Wheat"))))
     (gnus-group-mail-low-face ((t (:foreground "aquamarine4"))))
     (gnus-group-news-1-empty-face ((t (:foreground "PaleTurquoise"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (gnus-group-news-2-empty-face ((t (:foreground "turquoise"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "turquoise" :weight bold))))
     (gnus-group-news-3-empty-face ((t (:foreground "wheat"))))
     (gnus-group-news-3-face ((t (:bold t :foreground "Wheat" :weight bold))))
     (gnus-group-news-4-empty-face ((t (nil))))
     (gnus-group-news-4-face ((t (:bold t :weight bold))))
     (gnus-group-news-5-empty-face ((t (nil))))
     (gnus-group-news-5-face ((t (:bold t :weight bold))))
     (gnus-group-news-6-empty-face ((t (nil))))
     (gnus-group-news-6-face ((t (:bold t :weight bold))))
     (gnus-group-news-low-empty-face ((t (:foreground "MediumAquamarine"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "MediumAquamarine" :weight bold))))
     (gnus-header-content-face ((t (:italic t :foreground "Wheat" :slant italic))))
     (gnus-header-from-face ((t (:foreground "light yellow"))))
     (gnus-header-name-face ((t (:foreground "Wheat"))))
     (gnus-header-newsgroups-face ((t (:italic t :foreground "gold" :slant italic))))
     (gnus-header-subject-face ((t (:bold t :foreground "Gold" :weight bold))))
     (gnus-signature-face ((t (:italic t :foreground "white" :slant italic))))
     (gnus-splash-face ((t (:foreground "orange"))))
     (gnus-summary-cancelled-face ((t (:background "black" :foreground "orange"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "SkyBlue" :weight bold))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "red" :weight bold))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "coral" :weight bold))))
     (gnus-summary-high-unread-face ((t (:bold t :foreground "gold" :weight bold))))
     (gnus-summary-low-ancient-face ((t (:italic t :foreground "SkyBlue" :slant italic))))
     (gnus-summary-low-read-face ((t (:italic t :foreground "red" :slant italic))))
     (gnus-summary-low-ticked-face ((t (:italic t :foreground "coral" :slant italic))))
     (gnus-summary-low-unread-face ((t (:italic t :foreground "white" :slant italic))))
     (gnus-summary-normal-ancient-face ((t (:foreground "SkyBlue"))))
     (gnus-summary-normal-read-face ((t (:foreground "PaleGreen"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "pink"))))
     (gnus-summary-normal-unread-face ((t (:foreground "white"))))
     (gnus-summary-selected-face ((t (:foreground "white" :underline t))))
     (green ((t (:foreground "green"))))
     (gui-button-face ((t (:background "grey75" :foreground "black"))))
     (gui-element ((t (:background "#D4D0C8" :foreground "black"))))
     (header-line ((t (:background "grey90" :foreground "grey20" :box nil))))
     (help-argument-name ((t (nil))))
     (hi-black-b ((t (:bold t :weight bold))))
     (hi-black-hb ((t (:bold t :weight bold :height 1.67 :family "Sans Serif"))))
     (hi-blue ((t (:background "light blue"))))
     (hi-blue-b ((t (:bold t :foreground "blue1" :weight bold))))
     (hi-green ((t (:background "green1"))))
     (hi-green-b ((t (:bold t :foreground "green1" :weight bold))))
     (hi-pink ((t (:background "pink"))))
     (hi-red-b ((t (:bold t :foreground "red1" :weight bold))))
     (hi-yellow ((t (:background "yellow1"))))
     (highlight ((t (:background "darkolivegreen"))))
     (highlight-symbol-face ((t (:background "gray90"))))
     (highline-face ((t (:background "dark slate gray" :foreground "white"))))
     (hl-line ((t (:background "grey20"))))
     (holiday-face ((t (:background "red" :foreground "white"))))
     (ibuffer-deletion-face ((t (:foreground "red"))))
     (ibuffer-marked-face ((t (:foreground "green"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :foreground "Red1" :weight bold))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (info-header-node ((t (:italic t :bold t :foreground "brown" :slant italic :weight bold))))
     (info-header-xref ((t (:foreground "blue1" :underline t))))
     (info-menu-header ((t (:bold t :underline t :weight bold))))
     (info-menu-star ((t (:foreground "red1" :underline t))))
     (info-node ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :foreground "green" :weight bold))))
     (info-title-2 ((t (:bold t :foreground "lightblue" :weight bold))))
     (info-title-3 ((t (:bold t :weight bold))))
     (info-title-4 ((t (:bold t :weight bold))))
     (info-xref ((t (:bold t :foreground "light gray" :weight bold))))
     (info-xref-visited ((t (:foreground "magenta4" :underline t))))
     (isearch ((t (:background "palevioletred2" :foreground "brown4"))))
     (isearch-fail ((t (:background "RosyBrown1"))))
     (isearch-secondary ((t (:foreground "red3"))))
     (iswitchb-current-match ((t (:foreground "Blue1"))))
     (iswitchb-invalid-regexp ((t (:bold t :foreground "Red1" :weight bold))))
     (iswitchb-single-match ((t (:foreground "Firebrick"))))
     (iswitchb-virtual-matches ((t (:foreground "MediumOrchid4"))))
     (italic ((t (:italic t :slant italic))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (left-margin ((t (nil))))
     (link ((t (:foreground "blue1" :underline t))))
     (link-visited ((t (:foreground "magenta4" :underline t))))
     (linum ((t (:foreground "grey50"))))
     (list-mode-item-selected ((t (:background "gray68" :foreground "white"))))
     (magit-branch ((t (:bold t :weight bold))))
     (magit-diff-add ((((class color) (background dark)) (:foreground "lightgreen"))))
     (magit-diff-del ((t (:foreground "red"))))
     (magit-diff-file-header ((t (nil))))
     (magit-diff-hunk-header ((t (:italic t :slant italic))))
     (magit-diff-none ((t (nil))))
     (magit-header ((t (nil))))
     (magit-item-highlight ((((class color) (background dark)) (:background "grey20"))))
     (magit-item-mark ((t (:foreground "red"))))
     (magit-log-graph ((t (:foreground "grey11"))))
     (magit-log-head-label-bisect-bad ((t (:background "IndianRed1" :foreground "IndianRed4" :box 1))))
     (magit-log-head-label-bisect-good ((t (:background "light green" :foreground "dark olive green" :box 1))))
     (magit-log-head-label-default ((t (:background "Grey50" :box 1))))
     (magit-log-head-label-local ((t (:background "Grey85" :foreground "LightSkyBlue4" :box 1))))
     (magit-log-head-label-patches ((t (:background "IndianRed1" :foreground "IndianRed4" :box 1))))
     (magit-log-head-label-remote ((t (:background "Grey85" :foreground "OliveDrab4" :box 1))))
     (magit-log-head-label-tags ((t (:background "LemonChiffon1" :foreground "goldenrod4" :box 1))))
     (magit-log-message ((t (nil))))
     (magit-log-sha1 ((t (:foreground "firebrick"))))
     (magit-log-tag-label ((t (:background "LightGoldenRod"))))
     (magit-menu-selected-option ((t (:foreground "red"))))
     (magit-section-title ((t (:bold t :weight bold))))
     (makefile-space-face ((t (:background "hotpink" :foreground "white"))))
     (match ((t (:background "yellow1"))))
     (menu ((t (nil))))
     (message-cited-text-face ((t (:foreground "green"))))
     (message-header-cc-face ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (message-header-name-face ((t (:foreground "Gold"))))
     (message-header-newsgroups-face ((t (:italic t :bold t :foreground "gold" :slant italic :weight bold))))
     (message-header-other-face ((t (:foreground "lightGray"))))
     (message-header-subject-face ((t (:foreground "Yellow"))))
     (message-header-to-face ((t (:bold t :foreground "green2" :weight bold))))
     (message-header-xheader-face ((t (:foreground "sky blue"))))
     (message-mml-face ((t (:bold t :foreground "khaki" :weight bold))))
     (message-separator-face ((t (:background "aquamarine" :foreground "black"))))
     (minibuffer-prompt ((t (:foreground "light blue"))))
     (mode-line ((t (:background "darkslateblue" :foreground "yellow" :box (:line-width -1 :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :background "dark gray" :foreground "black" :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "grey90" :foreground "grey20" :box (:line-width -1 :color "grey75" :style nil) :weight light))))
     (modeline-mousable ((t (:background "dark gray" :foreground "black"))))
     (modeline-mousable-minor-mode ((t (:background "dark gray" :foreground "black"))))
     (mouse ((t (:background "white"))))
     (next-error ((t (:background "lightgoldenrod2"))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (p4-depot-added-face ((t (:foreground "blue"))))
     (p4-depot-deleted-face ((t (:foreground "red"))))
     (p4-depot-unmapped-face ((t (:foreground "grey30"))))
     (p4-diff-change-face ((t (:foreground "dark green"))))
     (p4-diff-del-face ((t (:foreground "red"))))
     (p4-diff-file-face ((t (:background "gray90"))))
     (p4-diff-head-face ((t (:background "gray95"))))
     (p4-diff-ins-face ((t (:foreground "blue"))))
     (paren-mismatch-face ((t (:bold t :background "white" :foreground "red" :weight bold))))
     (paren-no-match-face ((t (:bold t :background "white" :foreground "red" :weight bold))))
     (pointer ((t (nil))))
     (pp^L-highlight ((t (nil))))
     (primary-selection ((t (:background "blue"))))
     (qt-classes-face ((t (:foreground "Red"))))
     (query-replace ((t (:background "magenta3" :foreground "lightskyblue1"))))
     (red ((t (:foreground "red"))))
     (region ((t (:background "blue"))))
     (right-margin ((t (nil))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "darkslateblue"))))
     (shadow ((t (:foreground "grey50"))))
     (show-block-face1 ((t (:background "gray10"))))
     (show-block-face2 ((t (:background "gray15"))))
     (show-block-face3 ((t (:background "gray20"))))
     (show-block-face4 ((t (:background "gray25"))))
     (show-block-face5 ((t (:background "gray30"))))
     (show-block-face6 ((t (:background "gray35"))))
     (show-block-face7 ((t (:background "gray40"))))
     (show-block-face8 ((t (:background "gray45"))))
     (show-block-face9 ((t (:background "gray50"))))
     (show-paren-match ((t (:background "turquoise"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (sldb-catch-tag-face ((t (nil))))
     (sldb-condition-face ((t (nil))))
     (sldb-detailed-frame-line-face ((t (nil))))
     (sldb-frame-label-face ((t (nil))))
     (sldb-frame-line-face ((t (nil))))
     (sldb-local-name-face ((t (nil))))
     (sldb-local-value-face ((t (nil))))
     (sldb-non-restartable-frame-line-face ((t (nil))))
     (sldb-restart-face ((t (nil))))
     (sldb-restart-number-face ((t (:bold t :weight bold))))
     (sldb-restart-type-face ((t (:foreground "Purple"))))
     (sldb-restartable-frame-line-face ((t (:foreground "lime green"))))
     (sldb-section-face ((t (nil))))
     (sldb-topline-face ((t (nil))))
     (slime-error-face ((t (:underline "red"))))
     (slime-highlight-face ((t (:background "darkseagreen2" :underline nil))))
     (slime-inspector-action-face ((t (:bold t :foreground "Red1" :weight bold))))
     (slime-inspector-label-face ((t (:foreground "dark cyan"))))
     (slime-inspector-topline-face ((t (nil))))
     (slime-inspector-type-face ((t (:foreground "ForestGreen"))))
     (slime-inspector-value-face ((t (:foreground "MediumOrchid4"))))
     (slime-note-face ((t (:underline "brown4"))))
     (slime-repl-input-face ((t (:bold t :weight bold))))
     (slime-repl-inputed-output-face ((t (:foreground "Red"))))
     (slime-repl-output-face ((t (:foreground "VioletRed4"))))
     (slime-repl-output-mouseover-face ((t (:foreground "Red" :box (:line-width 1 :color "black" :style released-button)))))
     (slime-repl-prompt-face ((t (:foreground "Purple"))))
     (slime-repl-result-face ((t (nil))))
     (slime-style-warning-face ((t (:underline "brown"))))
     (slime-warning-face ((t (:underline "orange"))))
     (speedbar-button-face ((t (nil))))
     (speedbar-directory-face ((t (nil))))
     (speedbar-file-face ((t (:bold t :weight bold))))
     (speedbar-highlight-face ((t (nil))))
     (speedbar-selected-face ((t (:underline t))))
     (speedbar-tag-face ((t (nil))))
     (swbuff-current-buffer-face ((t (:bold t :foreground "red" :weight bold))))
     (text-cursor ((t (:background "yellow" :foreground "black"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red"))))
     (underline ((t (:underline t))))
;     (variable-pitch ((t (:family "helv"))))
     (vertical-border ((t (:background "grey90" :foreground "grey20" :box (:line-width -1 :color "grey75" :style nil) :weight light))))
     (vertical-divider ((t (nil))))
     (which-func ((t (:foreground "Blue1"))))
     (widget ((t (nil))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray" :foreground "black"))))
     (widget-inactive ((t (:foreground "light gray"))))
     (widget-single-line-field ((t (:background "dim gray" :foreground "black"))))
     (woman-bold-face ((t (:bold t :weight bold))))
     (woman-italic-face ((t (:foreground "beige"))))
     (woman-unknown-face ((t (:foreground "LightSalmon"))))
     (yellow ((t (:foreground "yellow"))))
     (zmacs-region ((t (:background "snow" :foreground "blue")))))))
(add-to-list 'color-themes '(my-color-theme  "candera" "Craig Andera"))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; 
;; Old settings
;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


;;  '(mode-line ((((class color) (min-colors 88)) (:background "#8888ff" :foreground "black" :box (:line-width -1 :style released-button)))))
;;  '(cursor ((t (:background "red"))))
;;  '(highline-face ((t (:background "grey20"))))
;;  '(hl-line ((t (:inherit highlight :background "grey20"))))
;;  '(magit-diff-add ((((class color) (background dark)) (:foreground "lightgreen"))))
;;  '(diff-added ((t (:inherit diff-changed :foreground "green"))))
;;  '(diff-removed ((t (:inherit diff-changed :foreground "red"))))
;;  '(magit-item-highlight ((((class color) (background dark)) (:background "grey20"))))
;;  '(nxml-attribute-colon-face ((t (:inherit nxml-name-face :foreground "blue"))))
;;  '(nxml-attribute-local-name-face ((t (:inherit nxml-name-face :foreground "blue"))))
;;  '(nxml-attribute-prefix-face ((t (:inherit nxml-name-face :foreground "blue"))))
;;  '(nxml-namespace-attribute-colon-face ((t (:inherit nxml-name-face :foreground "red"))))
;;  '(nxml-namespace-attribute-prefix-face ((t (:inherit nxml-name-face :foreground "red"))))
;;  '(nxml-namespace-attribute-xmlns-face ((t (:inherit nxml-name-face :foreground "red"))))
;;  )

;; (unless window-system
;;  (custom-set-faces 
;;   '(isearch-face ((t (:foreground "black" :background "yellow"))))))

