#!/usr/bin/env bash

set -e

# TODO: Use this on Mac to get the absolute path of the dir containing
# the script since we can't use readlink -f

# # Get absolute path of the script
# dir=`dirname $0`            # The directory where the script is 
# pushd "$dir" > /dev/null    # Go there
# CALLERPATH=$PWD             # Record the absolute path
# popd > /dev/null            # Return to previous dir

# echo $CALLERPATH

THIS_SCRIPT=`readlink -f $0`
THIS_DIR=`dirname $THIS_SCRIPT`

echo "Setting up candera's custom emacs setup to point to $THIS_DIR"

cd $THIS_DIR
git submodule init
git submodule update

mkdir -p ~/.emacs.d

ln -fs $THIS_DIR ~/.emacs.d/custom

if [ -f ~/.emacs ]; then
    cp --backup=numbered ~/.emacs ~/your-old.emacs
    rm -f ~/.emacs
fi

if [ -f ~/.emacs.d/init.el ]; then
    cp --backup=numbered ~/.emacs.d/init.el ~/.emacs.d/your-old-init.el
    rm -f ~/.emacs.d/init.el
fi

echo '(load "~/.emacs.d/custom/init.el")' > ~/.emacs.d/init.el