#!/usr/bin/env bash

set -e

THIS_SCRIPT=`readlink -f $0`
THIS_DIR=`dirname $THIS_SCRIPT`

echo "Setting up candera's custom emacs setup to point to $THIS_DIR"

cd $THIS_DIR
git submodule init
git submodule update

mkdir -p ~/.emacs.d

ln -fs $THIS_DIR ~/.emacs.d/custom

if [ -f ~/.emacs ]; then
    cp --backup=numbered ~/.emacs ~/your-old.emacs
    rm -f ~/.emacs
fi

if [ -f ~/.emacs.d/init.el ]; then
    cp --backup=numbered ~/.emacs.d/init.el ~/.emacs.d/your-old-init.el
    rm -f ~/.emacs.d/init.el
fi

echo '(load "~/.emacs.d/custom/init.el")' > ~/.emacs.d/init.el