#!/usr/bin/env bash

set -e

if [ "$(which makeinfo)" == "" ]; then
  echo 'texinfo package is not installed. Run `apt-get install texinfo` or equivalent.'
  exit 1
fi

# Use this on Mac to get the absolute path of the dir containing the
# script since we can't use readlink -f

if [ "$(uname)" == "Darwin" ]; then
# Get absolute path of the script by changing to that directory and
# using $PWD, which is always an absolute path
    dir=`dirname $0`		
    pushd "$dir" > /dev/null    
    THIS_SCRIPT=$PWD/$(basename $0)            
    popd > /dev/null           
else
    THIS_SCRIPT=`readlink -f $0`
fi

THIS_DIR=`dirname $THIS_SCRIPT`

echo "Setting up candera's custom emacs setup to point to $THIS_DIR"

cd $THIS_DIR
git submodule init
git submodule update

if [ "$1" == "--with-initial-setup" ]; then
    mkdir -p ~/.emacs.d

    ln -fs $THIS_DIR ~/.emacs.d/custom

    if [ -f ~/.emacs ]; then
        cp --backup=numbered ~/.emacs ~/your-old.emacs
        rm -f ~/.emacs
    fi

    if [ -f ~/.emacs.d/init.el ]; then
        cp --backup=numbered ~/.emacs.d/init.el ~/.emacs.d/your-old-init.el
        rm -f ~/.emacs.d/init.el
    fi

    echo '(load "~/.emacs.d/custom/init.el")' > ~/.emacs.d/init.el
fi

pushd org-mode
make
popd
